import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { Pool } from 'pg'

import { ECOMMERCE_SCHEMA } from '../lib/seed-data'

const connectionString = process.env.DATABASE_URL

const pool = new Pool({ connectionString })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

const USERS_SCHEMA = [
    "CREATE TABLE users (id INTEGER, name VARCHAR, role VARCHAR)",
    "INSERT INTO users VALUES (1, 'Alice', 'Engineer')",
    "INSERT INTO users VALUES (2, 'Bob', 'Sales')"
].join(';\n') + ';'

async function main() {
    const adminEmail = 'anchitgupt2012@gmail.com'
    await prisma.user.upsert({
        where: { email: adminEmail },
        update: { role: 'ADMIN' },
        create: {
            email: adminEmail,
            name: 'Anchit Gupta',
            role: 'ADMIN',
        },
    })

    const topic = await prisma.topic.upsert({
        where: { slug: 'data-engineering-101' },
        update: {},
        create: {
            name: 'Data Engineering 101',
            slug: 'data-engineering-101',
            description: 'Introduction to Data Engineering concepts.',
        },
    })

    await prisma.article.upsert({
        where: { slug: 'what-is-etl' },
        update: {},
        create: {
            title: 'What is ETL?',
            slug: 'what-is-etl',
            content: `
# What is ETL ?

** ETL ** stands for Extract, Transform, Load.

## Process
1. ** Extract **: Get data from source.
2. ** Transform **: Clean and format data.
3. ** Load **: Save to data warehouse.

\`\`\`python
def etl_process():
    data = extract()
    clean_data = transform(data)
    load(clean_data)
\`\`\`
      `,
            published: true,
            topicId: topic.id,
            authorId: 'system',
        },
    })

    const usersSchema = await prisma.sqlSchema.upsert({
        where: { name: 'users' },
        update: { sql: USERS_SCHEMA },
        create: { name: 'users', sql: USERS_SCHEMA },
    })

    const ecommerceSchema = await prisma.sqlSchema.upsert({
        where: { name: 'ecommerce' },
        update: { sql: ECOMMERCE_SCHEMA },
        create: { name: 'ecommerce', sql: ECOMMERCE_SCHEMA },
    })

    await prisma.sQLProblem.upsert({
        where: { slug: 'simple-select' },
        update: {
            sqlSchema: USERS_SCHEMA,
            schemaId: usersSchema.id,
        },
        create: {
            title: 'Simple Select',
            slug: 'simple-select',
            difficulty: 'EASY',
            description: 'Select all columns from the users table.',
            schemaDescription: 'Table `users` with columns: id, name, role',
            sqlSchema: USERS_SCHEMA,
            schemaId: usersSchema.id,
            expectedOutput: '[{"id":1,"name":"Alice","role":"Engineer"},{"id":2,"name":"Bob","role":"Sales"}]'
        }
    })

    await prisma.sQLProblem.upsert({
        where: { slug: 'total-revenue-per-customer' },
        update: {
            sqlSchema: ECOMMERCE_SCHEMA,
            schemaId: ecommerceSchema.id,
        },
        create: {
            title: 'Total Revenue Per Customer',
            slug: 'total-revenue-per-customer',
            difficulty: 'MEDIUM',
            description: 'Calculate the total revenue generated by each customer who has placed at least one order. Return columns `name` and `total_revenue`. Order by `total_revenue` descending.',
            sqlSchema: ECOMMERCE_SCHEMA,
            schemaId: ecommerceSchema.id,
            schemaDescription: 'Tables: customers, orders, order_items, products',
            expectedOutput: '[{"name":"John Doe","total_revenue":1450},{"name":"Alice Johnson","total_revenue":1350},{"name":"Jane Smith","total_revenue":800}]'
        }
    })

    await prisma.sQLProblem.upsert({
        where: { slug: 'top-selling-products' },
        update: {
            sqlSchema: ECOMMERCE_SCHEMA,
            schemaId: ecommerceSchema.id,
        },
        create: {
            title: 'Top Selling Products',
            slug: 'top-selling-products',
            difficulty: 'HARD',
            description: 'Find the top 3 products by total quantity sold. Return columns `name` and `total_sold`. Order by `total_sold` descending, then `name` ascending.',
            sqlSchema: ECOMMERCE_SCHEMA,
            schemaId: ecommerceSchema.id,
            schemaDescription: 'Tables: products, order_items',
            expectedOutput: '[{"name":"Desk Chair","total_sold":2},{"name":"Laptop","total_sold":2},{"name":"Headphones","total_sold":1}]'
        }
    })

    console.log('Seed data created.')
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        if (e.code === 'P2002') return
        console.error(e)
        process.exit(1)
    })
