// Unit tests for analytics reporting windows.
// No React, DOM, or database.
//
// Run: node --import tsx --test scripts/test-analytics-windows.ts

import assert from "node:assert/strict"
import { describe, it } from "node:test"
import {
    MAX_WINDOW_DAYS,
    assertWindow,
    dailySeries,
    previousWindowBounds,
    windowBounds,
} from "../lib/analytics/metric-windows"
import { buildHeatmap, toDayKey } from "../lib/profile-stats"

const DAY_MS = 24 * 60 * 60 * 1000
const END_DAY = new Date("2026-03-15T09:30:00.000Z")

describe("assertWindow", () => {
    it("accepts the maximum supported window", () => {
        assert.doesNotThrow(() => assertWindow(MAX_WINDOW_DAYS))
    })

    it("rejects non-integers and values outside the supported range", () => {
        for (const value of [366, 0, -1, 7.5]) {
            assert.throws(() => assertWindow(value), RangeError)
        }
    })
})

describe("windowBounds", () => {
    it("anchors a seven-day window to UTC midnights", () => {
        const bounds = windowBounds(7, END_DAY)

        assert.equal(bounds.start.toISOString(), "2026-03-09T00:00:00.000Z")
        assert.equal(bounds.end.toISOString(), "2026-03-16T00:00:00.000Z")
    })

    it("covers exactly thirty whole days", () => {
        const bounds = windowBounds(30, END_DAY)

        assert.equal(bounds.end.getTime() - bounds.start.getTime(), 30 * DAY_MS)
    })
})

describe("previousWindowBounds", () => {
    it("touches the current window without a gap or overlap", () => {
        const current = windowBounds(7, END_DAY)
        const previous = previousWindowBounds(7, END_DAY)

        assert.equal(previous.end.getTime(), current.start.getTime())
        assert.equal(
            previous.end.getTime() - previous.start.getTime(),
            7 * DAY_MS
        )
    })
})

describe("dailySeries", () => {
    it("returns seven zero-filled days for an empty window", () => {
        assert.deepEqual(dailySeries([], 7, END_DAY), [
            { date: "2026-03-09", count: 0 },
            { date: "2026-03-10", count: 0 },
            { date: "2026-03-11", count: 0 },
            { date: "2026-03-12", count: 0 },
            { date: "2026-03-13", count: 0 },
            { date: "2026-03-14", count: 0 },
            { date: "2026-03-15", count: 0 },
        ])
    })

    it("keeps a 23:59:59Z timestamp on its UTC day", () => {
        const submittedAt = new Date("2026-03-12T23:59:59.000Z")
        const series = dailySeries([submittedAt], 7, END_DAY)

        assert.deepEqual(series[3], { date: "2026-03-12", count: 1 })
    })

    it("uses the profile heatmap's UTC day-key convention", () => {
        const submittedAt = new Date("2026-03-12T23:59:59.000Z")
        const series = dailySeries([submittedAt], 7, END_DAY)

        assert.equal(series[3].date, toDayKey(submittedAt))
    })

    it("returns the exact series generated by buildHeatmap", () => {
        const dates = [
            new Date("2026-03-10T08:00:00.000Z"),
            new Date("2026-03-10T22:00:00.000Z"),
            new Date("2026-03-15T01:00:00.000Z"),
        ]

        assert.deepEqual(
            dailySeries(dates, 7, END_DAY),
            buildHeatmap(dates, 7, END_DAY)
        )
    })

    it("rejects an oversized window instead of silently clamping", () => {
        assert.throws(() => dailySeries([], 366, END_DAY), RangeError)
    })
})
